travis:
  secure:
    BINSTAR_TOKEN: KJm+1KmDSr4EV/GBBsP6kafIe50kaqOzmwLXr5w3aEs3nRQS4tNTE2D34sZA3BCI3z0UsBEt3abMwqXqlsqdWyKyNEVZ0JB69LQjH3Axb2Cyd5iQXmvXIaNCdpGeb01pU4agy0YjUTYSEuJOCzFZ8FcnThqoSyS/HussdVbCIL0xTEzg+MFz9b0sPGCVV/WISAqhYDYu/i5u4hi9B5pw2xCv6WGmRpwgsnSqPx6+Db57F60wiJHtjrH3YVxVzSTnOdhGizGF36k58k+R3P3i0n/ksxkl5TnGUs7ZJveRV4o3H3iqz95t8Jyeh2ii+W99rK+w0N1PCeJjDDiGOlZUbfAGAG2Jda/5unn9RdHaNK64swZBNj2sn3n9y6C0GsivjT5ePpQgMgz/HCD8plDc58aitAtBGXC5mMKhEvGG4J7abeN5c4bdruVpDG/h2vCKvHUTuy529i2OjhJZNWi1xIvdiCK3uKvLgX8D2IiRno8/xNSDKbSJu3r64WplH5gXJxQj3CrZlfe1wMSlUhgJjVQKHONxtYwbEal4my4wbcLUtnXi8XiU4RpE06DoXvw/WNU6PKxqvxZAgx82/TJRppKb2kDDukovu6VdWoFXybhVdrE1pMtoYUyNjkwREAMZy/LbenlduG/4CJu/xh/8jRYZEMAPhOnhR+Ri3LgvMRo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
